services:
  backend:
    image: germantarnoski/quirknotes_backend:latest
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  frontend:
    image: germantarnoski/quirknotes_frontend:latest
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: frontend
    ports:
      - "3000:3000"
    environment:
      - ENV=Docker
    depends_on:
      - backend


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"